[font]
normal = { family = "0xProto Nerd Font", style = "Regular" }
size = 12  # 可以根据屏幕调整

[font.bold]
style = "Bold"

[font.italic]
style = "Italic"

[font.bold_italic]
style = "Bold Italic"

[window]
decorations = "none"
startup_mode = "Maximized"
opacity = 0.92

[general]
import = ["/usr/share/alacritty/themes/catppuccin_mocha.toml"]
